#Configuracao do banco
#spring.datasource.url=jdbc:mysql://localhost/advApi
#string.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.datasource.username=root
#spring.datasource.password=12345678

#Configuracao MYSQL Dev
server.port = 8080
#spring.datasource.url=jdbc:mysql://localhost:3306/advApi?useSSL=false&createDatabaseIfNotExist=TRUE
#spring.datasource.username=root
#spring.datasource.password=laurinha!2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#Conexao com o railway
spring.datasource.url=jdbc:mysql://root:SjJnrQhgEwPokBHjIaCAoaiFGyfGjDSV@junction.proxy.rlwy.net:29551/railway?useSSL=false&createDatabaseIfNotExist=TRUE
spring.datasource.username=root
spring.datasource.password=SjJnrQhgEwPokBHjIaCAoaiFGyfGjDSV


#Configuracao aws
#server.port = 5000
#spring.datasource.url=jdbc:mysql://thomdb.c9meqium4786.us-east-2.rds.amazonaws.com:3306/advApi?useSSL=false&createDatabaseIfNotExist=TRUE
#spring.datasource.username=root
#spring.datasource.password=laurinha!2


#Operacoes de banco JPA


#spring.jpa.properties.hibernate.jdbc.time_zone=UTC
#jdbc:mysql://<ip>/<db>?serverTimezone=TimeZone&useLegacyDatetimeCode=false
#todolist.originPermitida=http://localhost:4200

#config jackson
spring.jackson.default-property-inclusion:NON_NULL
spring.jackson.date-format:dd-MM-yyyy

#mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dariojr1233@gmail.com
spring.mail.recipient=contato@thomasvcg.com
spring.mail.password=kvufesonkpnvpzbf
spring.googlereview.apikey=AIzaSyAWMjDZcTFLGb-l46pqjCenN6XZHlljBLY
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.writetimeout: 10000
spring.mail.properties.mail.smtp.connectiontimeout: 10000
spring.mail.properties.mail.smtp.timeout: 10000